name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Setup config files
        run: echo '${{ secrets.SESSION_SECRET }}' > session-secret.json; echo '${{ secrets.ORMCONFIG }}' > ormconfig.json

      - name: Build application
        run: npm run build

      - name: Run migrations
        run: npm run migrate

      - name: (Re)start application
        run: npm run restart
